name: dio_lista_contatos
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  image_picker: ^1.0.4
  image_cropper: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
